= Supported blocks

== system

The `system` block is used to configure system-wide settings. It can contain the following keys:

[cols="1,1,1,5"]
|===
|Attribute |Type |Required |Description

|hostname
|string
|Yes
|The hostname of the machine.

|timezone
|string
|No
|The timezone of the machine (e.g., `"UTC"`, `"America/New_York"`).

|enable_tty_auto_login
|bool
|No
|Enable automatic login on the console.

|power_profile
|string
|No
|The power profile to use (e.g., `"performance"`, `"ondemand"`, `"powersave"`).

|updates
|sub-block
|No
|The `updates` sub-block configures Flatcar OS update settings.

|===

=== updates

[cols="1,1,1,5"]
|===
|Attribute |Type |Required |Description

|reboot_strategy
|string
|No
|The reboot strategy for updates (one of: `"off"`, `"reboot"`, `"etcd-lock"`).
|===

Example:

[source,hcl]
----
system {
  hostname = "cola"
  timezone = "UTC"
  enable_tty_auto_login = true
  power_profile = "performance"

  updates {
    reboot_strategy = "reboot"
  }
}
----

== user

The `user` block is used to configure user accounts.

[cols="1,1,1,5"]
|===
|Attribute |Type |Required |Description

|uid
|int
|No
|The user ID.

|groups
|list(string)
|No
|The groups the user belongs to.

|shell
|string
|No
|The user's shell.

|home_dir
|string
|No
|The user's home directory.

|no_create_home
|bool
|No
|Do not create the user's home directory.

|ssh_authorized_keys
|list(string)
|No
|The user's SSH authorized keys.
|===

You the username is specified using the block label.

Example:

[source,hcl]
----
user "alice" {
  uid    = 1000
  groups = ["wheel"]
  shell  = "/bin/bash"
  home_dir = "/home/alice"
  ssh_authorized_keys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZlJ7...",
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZlJ7..."
  ]
}
----

== extension

The `extension` block is used to configure Systemd sysext extensions.
You must specify the `name` as the block label.

[cols="1,1,1,5"]
|===
|Attribute |Type |Required |Description

|version
|string
|Yes
|The version of the extension.

|arch
|string
|No
|The architecture of the extension (e.g., `"x86_64"`, `"arm64"`).

|bakery_url
|string
|Yes
|The URL of the extension's bakery.
|===


Example:

[source,hcl]
----
extension "consul" {
  version    = "1.9.5"
  arch       = "x86_64"
  bakery_url = "https://bakery.example.com/"
}
----

== container

The `container` block is used to configure containers.
You must specify the `name` as the block label.

[cols="1,1,1,5"]
|===
|Attribute |Type |Required |Description

|image
|string
|Yes
|The container image.

|args
|list(string)
|No
|The arguments to pass to the container.

|restart
|string
|No
|The container restart policy (e.g., `"always"`, `"on-failure"`).

|cap_add
|list(string)
|No
|Additional Linux capabilities to add to the container.

|volume
|sub-block
|No
|One or more `volume` sub-blocks that configure container volumes.
|===

Example:

[source,hcl]
----
container "nginx" {
  image   = "nginx:latest"
  args    = ["-p", "80:80"]
  restart = "always"

  volume "/var/www" {
    source = "/var/www"
  }
}
----

=== volume

The `volume` sub-block is used to configure container volumes.
You must specify the target mount path as the block label.

[cols="1,1,1,5"]
|===
|Attribute |Type |Required |Description

|source
|string
|Yes
|The path on the host that is mounted into the container.
|===

Example:

[source,hcl]
----
container "myapp" {
  image = "myapp:1.0"

  volume "/opt/myapp/config" {
    source = "/etc/myapp"
  }
}
----

== file

The `file` block is used to manage the creation or modification of files.
You must specify the `path` as the block label.

[cols="1,1,1,5"]
|===
|Attribute |Type |Required |Description

|owner
|string
|No
|The file owner.

|group
|string
|No
|The file group.

|mode
|string
|Yes
|The file permissions.

|inline
|string
|No
|The file contents provided inline.

|source_path
|string
|No
|Path to a local file whose contents should be used.

|url
|string
|No
|Remote URL whose contents should be fetched and used.

|overwrite
|bool
|No
|Overwrite the file if it already exists.
|===

Example:

[source,hcl]
----
file "/etc/myconfig.conf" {
  owner = "root"
  group = "root"
  mode  = "0644"

  inline = <<-EOF
    # This is my config
    setting1 = true
    setting2 = "some-value"
  EOF

  # Alternatively, you can use a local file or a URL.
  # Relative paths are resolved relative to the configuration file.
  # source_path = "/path/to/local/file"
  # url = "https://example.com/myconfig.conf"
  # overwrite = true
}
----

== directory

The `directory` block is used to manage directories on the system.
You must specify the `path` as the block label.

[cols="1,1,1,5"]
|===
|Attribute |Type |Required |Description

|owner
|string
|No
|The directory owner.

|group
|string
|No
|The directory group.

|mode
|string
|Yes
|The directory permissions.

|overwrite
|bool
|No
|Overwrite the directory if it already exists.

|recursive
|bool
|No
|Create parent directories if they do not exist.
|===


Example:

[source,hcl]
----
directory "/var/log/myapp" {
  owner = "myapp"
  group = "myapp"
  mode  = "0750"
}
----

== symlink

The `symlink` block is used to create symbolic links.
You must specify the link `path` as the block label.

[cols="1,1,1,5"]
|===
|Attribute |Type |Required |Description

|target
|string
|Yes
|The file or directory the symlink should point to.

|owner
|string
|No
|The symlink owner.

|group
|string
|No
|The symlink group.

|overwrite
|bool
|No
|Overwrite the symlink if it already exists.
|===

Example:

[source,hcl]
----
symlink "/usr/bin/myapp" {
  target    = "/opt/myapp/myapp"
  owner     = "root"
  group     = "root"
  overwrite = true
}
----

== mount

The `mount` block is used to configure file system mounts.
You must specify the `mount_point` as the block label.

[cols="1,1,1,5"]
|===
|Attribute |Type |Required |Description

|type
|string
|Yes
|The filesystem type (e.g., `"ext4"`, `"nfs"`, `"tmpfs"`).

|what
|string
|Yes
|The source device or remote path.

|where
|string
|Yes
|Where to mount in the filesystem (mount target).

|options
|string
|No
|Additional mount options (comma-separated).
|===

Example:

[source,hcl]
----
mount "/data" {
  type    = "ext4"
  what    = "/dev/sdb1"
  where   = "/data"
  options = "defaults"
}
----

== interface

The `interface` block is used to configure network interfaces.

[cols="1,1,1,5"]
|===
|Attribute |Type |Required |Description

|name
|string
|No
|The interface name (e.g., `"eth0"`).

|mac_address
|string
|No
|The desired MAC address for the interface.

|gateway
|string
|No
|The default gateway.

|address
|string
|No
|The IPv4 or IPv6 address with CIDR (e.g., `"192.168.1.10/24"`).

|addresses
|list(string)
|No
|An array of IPv4 or IPv6 addresses with CIDR. Mutually exclusive with `address`.

|dns
|string
|No
|DNS nameserver address (e.g., `"8.8.8.8"`).

|dhcp
|bool
|No
|Whether to enable DHCP on this interface.

|vlan
|sub-block
|No
|One or more `vlan` sub-blocks for VLAN configuration.
|===

Example:

[source,hcl]
----
interface {
  name        = "eth0"
  mac_address = "00:1A:2B:3C:4D:5E"
  address     = "192.168.1.10/24"
  gateway     = "192.168.1.1"
  dns         = "8.8.8.8"
  dhcp        = false

  vlan "vlan10" {
    id      = 10
    address = "192.168.10.10/24"
    gateway = "192.168.10.1"
    dns     = "8.8.8.8"
    dhcp    = false
  }
}
----

=== vlan

The `vlan` sub-block is used to define VLANs on top of an interface.
You must specify the VLAN `name` as the block label.

[cols="1,1,1,5"]
|===
|Attribute |Type |Required |Description

|id
|int
|Yes
|The VLAN ID number.

|address
|string
|No
|The VLAN's address with CIDR notation.

|gateway
|string
|No
|The VLAN's default gateway.

|dns
|string
|No
|The VLAN's DNS server.

|dhcp
|bool
|No
|Whether to enable DHCP on this VLAN.
|===


== service

The `service` block is used to configure systemd services.
You must specify the service `name` as the block label.

[cols="1,1,1,5"]
|===
|Attribute |Type |Required |Description

|inline
|string
|No
|The full systemd unit file content provided inline.

|source_path
|string
|No
|A path to a local file containing the systemd unit file.

|enabled
|bool
|No
|Whether to enable (and start) the service.
|===

Example:

[source,hcl]
----
service "myapp" {
  inline = <<-EOF
    [Unit]
    Description=My Application

    [Service]
    ExecStart=/usr/bin/myapp

    [Install]
    WantedBy=multi-user.target
  EOF

  enabled = true

  drop_in "logging.conf" {
    inline = <<-EOF
        [Service]
        Environment="LOG_LEVEL=debug"
    EOF
  }
}
----

=== drop_in

The `drop_in` sub-block is used to define systemd drop-in files for a service.
You must specify the drop-in `name` as the block label.

[cols="1,1,1,5"]
|===
|Attribute |Type |Required |Description

|inline
|string
|No
|The contents of the drop-in file provided inline.

|source_path
|string
|No
|A path to a local file containing the drop-in configuration.
|===

== etcd

The `etcd` block is used to configure the integrated etcd service.
Both servers and gateways require at least one `peer` block to be defined.

[cols="1,1,1,5"]
|===
|Attribute |Type |Required |Description

|name
|string
|Yes
|The name of the etcd member.

|server
|bool
|No
|Whether this member is a server.

|gateway
|bool
|No
|Whether this member is a gateway.

|listen_address
|string
|Yes (for servers)
|The listen address for the etcd member.

|initial_token
|string
|Yes (for servers)
|The initial cluster token.
|===

=== peer

The `peer` sub-block is used to configure etcd cluster peers.

[cols="1,1,1,5"]
|===
|Attribute |Type |Required |Description

|name
|string
|Yes
|The name of the peer.

|address
|string
|Yes
|The peer address.

|port
|int
|Yes
|The peer port.
|===

Example:

[source,hcl]
----
etcd {
  name = "etcd1"
  server = true
  listen_address = "10.0.0.5"
  initial_token = "etcd-cluster-1"

  peer "etcd2" {
    address = "10.0.0.6"
    port = 2380
  }

  peer "etcd3" {
    address = "10.0.0.7"
    port = 2380
  }
}
----

== variable

The `variable` block is used to define variables that can be referenced in other blocks.
You must specify the variable `name` as the block label.

[cols="1,1,1,5"]
|===
|Attribute |Type |Required |Description

|name
|string
|Yes
|The name of the variable.

|type
|type
|Yes
|The type of the variable. (e.g., `string`, `number`, `boolean`).
|===

Example:

[source,hcl]
----
variable "myvar" {
  type = string
}
----

[source,hcl]
----
variable "myvar" {
  type = number
}
----

Variables can be referenced using the `${var.myvar}` syntax.

Example:

[source,hcl]
----
file "/etc/myconfig.conf" {
  owner = "root"
  group = "root"
  mode  = "0644"
  inline = <<-EOF
    myvar = "${var.myvar}"
  EOF
}
----
